export const content = [
  `Ga Ming is extremely professional and courteous in his approach, and has demonstrated excellent problem solving and an ability to learn quickly.  Following great academic achievements at A-Level and achieving his Gold DofE award, Ga Ming joined our twelve week Master coding bootcamp, to forge a career in software development. \n\nGa Ming is driven to achieve, and has a well balanced approach to his work. He is committed and dedicated to learning, will offer support where needed and works well as part of a team. Ga Ming has enjoyed the entire bootcamp, and has demonstrated great strengths across the stack, with a real passion for front end, creative work. Ga Ming has a commercial mind set and would love to combine his interests in both coding and business studies.`,
  "Jenny has recently discovered a love of coding and is passionate about using her skills to forge a career in software development. Jenny is a career changer, having previously worked in administration, education and retail – therefore offers varied commercial experience in addition to her coding skills. \n\nHaving completed our three week level two course, along with our twelve week Master coding bootcamp, Jenny is ready to build upon these skills in the workplace. Jenny is a committed and determined problem solver, with a real ability to work well as part of a team – both working well collaboratively but also supporting others. \n\nJenny is keen to further her learning and use her skills across full stack development.",
  "Mike is a very competent coder with a real skill of learning independently. He picks up new concepts quickly, and works tirelessly to complete the task in hand. Mike has completed both our level 2 three week coding course along with our twelve week master coding bootcamp, having joined Code Nation following an extensive career in the hospitality industry. \n\nMike is passionate about coding, is very logical and methodical in his approach and has a love of back end development. He would like to further his skills across the full stack, but has a natural bias for database development.",
  "John has received impressive feedback from the Code Nation Instructor team. Following completion of his A-Levels, John has undertaken our three week level 2 coding course, followed by our twelve week Master coding bootcamp. John is a natural but modest high-achiever; quality driven, positive and resilient, with a real creative flair. \n\nJohn is a proven fast learner and has a real eye for detail. Whilst solid across full stack development, John has some great styling and design skills, with design being a great passion of his. He has also really enjoyed learning React. John would be a great addition to any team – demonstrating an ability to take the lead, whilst equally being at home supporting others. \n\nA great all-rounder, John has travelled to Africa where he worked on conservation projects, has held the position of Head Chorister at Chester Cathedral Choir and set up a business, all outside of his educational achievements.",
  "Matthew is a really creative individual, with a passion for software development, alongside his passion for photography and videography. Matthew has run his own videography business, therefore offers a wider commercial mindset in addition to a great foundation is coding. \n\nMatthew has completed our level two three week coding course and our twelve week Master Coding bootcamp. He is a great team player and has a real love of supporting and connecting with others. He enjoys working with others collaboratively and has a real passion for anything that enables him to apply his creativity.",
  "Ross has completed our level two three week course and our twelve week Master Coding bootcamp. Ross has applied himself well across the programme, and has really developed and widened his skillset. From full stack development, problem solving and team work, through to leading teams and playing an important role in group projects. \n\nRoss would love to continue his learning whilst contributing to an organisation, and is committed to a career in something he is passionate about. \n\nOutside of coding, Ross has a love of gaming and spends time with his pet dog.",
  "Following completion of a level three qualification, Liam joined Code Nation’s twelve week Master Coding bootcamp. Liam is a quick learner, equally at home working independently or as part of a team and has contributed well to projects. \n\nLiam is competent across full stack development, but has demonstrated a natural strength for back end database activity. Liam is quietly confident, able to ask for help when needed but balances this well with his strong ability to problem solve. \n\nLiam is an active member of the community, with previous experience of working as a lifeguard, coupled with an active involvement in his local scouting organisation.",
];
